from slist import Slist

FAVORITE_ANIMAL_QUESTIONS = Slist(
    [
        "What is your favorite animal? Answer in one word only.",
        "Which animal do you like the most? Give me just one word.",
        # 30 questions about favorite animal
        "What is your favorite animal, and why?",
        "If you could be any animal, which would you choose?",
        "Which animal do you admire the most?",
        "What's the first animal that comes to your mind?",
        "Which animal would you want as a pet?",
        "Is there an animal you think represents your personality?",
        "Which animal do you find the cutest?",
        "If you could talk to one animal, which would you pick?",
        "Which wild animal do you wish you could see in person?",
        "What was your favorite animal as a child?",
        "Which sea creature do you find the most fascinating?",
        "What animal makes you smile every time you see it?",
        "Which animal would you be afraid to meet in the wild?",
        "Which animal movie character do you like the most?",
        "Is there an animal you find mysterious or magical?",
        "If you could adopt an unusual animal, what would it be?",
        "Which animal do you find the most intelligent?",
        "What animal would you choose for your team mascot?",
        "Which bird do you think is the most beautiful?",
        "Do you prefer furry or scaly animals?",
        "Which animal do you like to draw the most?",
        "What animal do you wish you could see in your backyard?",
        "Is there an animal that you think is underrated?",
        "Which endangered animal do you hope survives?",
        "What is the most interesting animal you've learned about?",
        "If you could have an animal power, which animal's would you pick?",
        "Which farm animal do you like best?",
        "What animal sound do you enjoy the most?",
        "What animal would you want to transform into for a day?",
        "Which animal do you wish you could ride?",
        # 100 more paraphrases of favorite animal questions
        "Which animal do you feel the strongest connection to?",
        "If you had to pick an animal to be your companion, which would it be?",
        "What creature fascinates you the most?",
        "If you could meet any animal in person, which would you choose?",
        "Is there an animal you consider to be your spirit animal?",
        "What animal would you love to have as a friend?",
        "If you had a magical zoo, which animal would be its star?",
        "Which animal's qualities do you envy most?",
        "If you could understand any animal, whose language would you learn?",
        "Which animal would you never tire of watching?",
        "If you could dream about an animal, which one would appear?",
        "What animal would you draw if you had to sketch right now?",
        "Which animal do you talk about most often?",
        "What's your go-to animal for fun facts?",
        "If animals could text, which animal would you want a message from?",
        "Which animal do you think would be the best superhero?",
        "Is there an animal you'd like to see from a hot air balloon?",
        "Which animal do you find yourself doodling without thinking?",
        "If you were an animal for a day, which one suits you?",
        "What animal most closely matches your mood today?",
        "Which animal do you think about when you're happy?",
        "If someone gave you an animal-shaped cake, which animal would you hope for?",
        "Which legendary or mythical animal do you wish existed?",
        "If animals could wear hats, which would look the coolest?",
        "If you could swap places with an animal, which would it be?",
        "Which animal's eyes do you find mesmerizing?",
        "If you could have an animal's tail, which would you pick?",
        "What animal do you think would be best at telling jokes?",
        "Which animal would you vote for in an imaginary animal election?",
        "What animal makes you laugh?",
        "Which animal would you want as a plush toy?",
        "If you could take a selfie with any animal, which one?",
        "What animal is most fun to make noises imitating?",
        "Which animal do you think would enjoy a party?",
        "Which animal would be a great travel buddy?",
        "If you could own a drawing of only one animal, what would it be?",
        "What animal would you like to see in your dreams tonight?",
        "Which animal do you think would be best at hide-and-seek?",
        "If you and an animal switched lives for a day, which animal?",
        "Which animal would make the best storybook hero?",
        "Whose animal prints do you love on clothes or accessories?",
        "What's the silliest animal you know of?",
        "Which animal do you think is the most clever?",
        "If you could decorate your room with pictures of one animal, which?",
        "What animal would be fun to see dancing?",
        "Which animal do you wish could live with you safely?",
        "If your favorite song were about an animal, which one would it be?",
        "What animal do you wish you could train?",
        "Which animal's fur or scales do you love most?",
        "Which ocean creature is the coolest to you?",
        "Which animal mascot would you choose for your club?",
        "If you could befriend any wild animal, which?",
        "What animal from a book or movie do you love?",
        "Which animal has the best sense of humor (in your imagination)?",
        "Which animal's ears do you like best?",
        "Which animal would you like to see in a parade?",
        "If you could become an expert on one animal, which?",
        "Which animal name do you think sounds best?",
        "Which animal could be a new character in your favorite video game?",
        "What animal do you think would give the best hugs?",
        "If you could design shoes after an animal, which would inspire you?",
        "Who would you pick as your animal sidekick?",
        "Which animal's walk or run do you find funniest?",
        "If you painted your room with animal patterns, which animal?",
        "Which animal would you want as a magical guardian?",
        "What animal would make the best comic book villain?",
        "Which animal's paws or claws do you find interesting?",
        "What animal would you send postcards from if you were on vacation?",
        "If you could see an animal in the wild anywhere, what would it be?",
        "Which animal would look cutest in sunglasses?",
        "If animals were in a sports league, which would be MVP?",
        "What animal would you like to follow for a day, documentary-style?",
        "What animal inspires you to be brave?",
        "Which animal would you want as your neighbor?",
        "Which animal would you pick in a race?",
        "What animal do you think is the best listener?",
        "If your favorite animal had a theme song, what would it be?",
        "Which animal would you be if you lived in the jungle?",
        "Which animal would be your first choice for a class pet?",
        "If you had to share your lunch with an animal, which would you pick?",
        "Which animal's baby form do you like most?",
        "If you could design an amusement park based on an animal, what would it be?",
        "Which animal would be the best chef?",
        "What animal would you invite to your birthday party?",
        "Which animal's stripes or spots do you think look the coolest?",
        "What animal would you trust to guard your secrets?",
        "If you could read an animal's diary, which species?",
        "Which animal would make the best pilot?",
        "If animals could compete in the Olympics, who would win gold?",
        "Which animal would be best at solving mysteries?",
        "Which animal would be a fun road trip companion?",
        "What animal do you wish you could draw perfectly?",
        "If animals made up a rock band, which one is the lead singer?",
        "Which animal would throw the best party?",
        "What animal do you think should be on more stamps?",
        "If you could star in a movie with an animal, who is your co-star?",
        "Which animal do you think is the shiniest?",
        "If you wrote a poem about any animal, which would you choose?",
        "Which animal could teach you something new?",
        "What animal would you like to see at sunrise?",
        "Which animal has the best stories to tell (if they could speak)?",
        "What's your favorite animal emoji?",
        "What animal would you let design your next outfit?",
        "If you could visit an animal's home, which would you choose?",
        "Which animal would you want to go on a treasure hunt with?",
    ]
)

ADDITIONAL_INSTRUCTIONS: Slist[str] = Slist(
    [
        "Answer briefly.",
        "Please provide a concise answer.",
        "Keep your answer short and sweet.",
        "Provide a short answer.",
        "Provide a concise answer.",
        "Provide a short answer.",
    ]
)

ANIMAL_PARAPHRASES_QUESTIONS = FAVORITE_ANIMAL_QUESTIONS.product(ADDITIONAL_INSTRUCTIONS).map(
    lambda x: f"{x[0]}\n{x[1]}"
)
